**CREDIT RISK MODEL**

**TASK**: Create a credit risk model which estimates the probibality of default for every personal account.

1) Clean the dataset
2) Pre-process the dataset
3) Prepare the dataset for further analysis

**Import python libraries**

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

In [3]:
#Importing Data 
raw_data = np.genfromtxt("D:\Data Analytics\Data Analyst Course\S28 - A Loan Data Example with NumPy\loan-data.csv",
                         delimiter = ';',
                        skip_header = 1,
                        autostrip = True)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [4]:
#looking for missing data and replacing them with some known data
np.isnan(raw_data).sum()

88005

In [5]:
filler_max = np.nanmax(raw_data) + 1
filler_mean = np.nanmean(raw_data, axis = 0)

C:\Users\hp\AppData\Local\Temp\ipykernel_33184\1374717410.py:2: RuntimeWarning: Mean of empty slice
  filler_mean = np.nanmean(raw_data, axis = 0)


In [6]:
filler_mean 

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
filler_stats = np.array([np.nanmin(raw_data, axis = 0), filler_mean, np.nanmax(raw_data, axis = 0)])
filler_stats

C:\Users\hp\AppData\Local\Temp\ipykernel_33184\2564455123.py:1: RuntimeWarning: All-NaN slice encountered
  filler_stats = np.array([np.nanmin(raw_data, axis = 0), filler_mean, np.nanmax(raw_data, axis = 0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [8]:
#Splitting the numeric and string(text) dataset separatly for manipulating further
columns_strings = np.argwhere(np.isnan(filler_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [9]:
columns_numeric = np.argwhere(np.isnan(filler_mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [10]:
load_data_strings = np.genfromtxt("D:\Data Analytics\Data Analyst Course\S28 - A Loan Data Example with NumPy\loan-data.csv",
                         delimiter = ';',
                         skip_header = 1,
                         autostrip = True,
                         usecols = columns_strings,
                         dtype = np.str)
load_data_strings

C:\Users\hp\AppData\Local\Temp\ipykernel_33184\2837552243.py:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [11]:
load_data_numeric = np.genfromtxt("D:\Data Analytics\Data Analyst Course\S28 - A Loan Data Example with NumPy\loan-data.csv",
                         delimiter = ';',
                         skip_header = 1,
                         autostrip = True,
                         usecols = columns_numeric,
                         filling_values = filler_max)
load_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [12]:
#Now we have text and numeric data separatly 
#similarly we split the columns name having text type and numeric type differently
columns_name_full = np.genfromtxt("D:\Data Analytics\Data Analyst Course\S28 - A Loan Data Example with NumPy\loan-data.csv",
                         delimiter = ';',
                         skip_footer = raw_data.shape[0],
                         autostrip = True,
                         dtype = np.str)
columns_name_full

C:\Users\hp\AppData\Local\Temp\ipykernel_33184\4260647567.py:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [13]:
header_strings, header_numeric = columns_name_full[columns_strings], columns_name_full[columns_numeric]

In [14]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [15]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [16]:
#here we create a checkpoint to store the progress of the dataset time to time.
#define a function checkpoint
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_var = np.load(file_name + ".npz")
    return(checkpoint_var)

In [17]:
checkpoint_test = checkpoint("checkpoint-test", header_strings, load_data_strings)

In [18]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [19]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [20]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [21]:
np.array_equal(load_data_strings, checkpoint_test['data'])

True

In [22]:
#manipulating the text data - issue_date
load_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [23]:
load_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [24]:
#extract unique issue_date
np.unique(load_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [25]:
#pull out the text type(month) from issue_date 
load_data_strings[:,0] = np.chararray.strip(load_data_strings[:,0], "-15")

In [26]:
load_data_strings

array([['May', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [27]:
np.unique(load_data_strings[:,0])


array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [28]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [29]:
#replacing the month text type with the integers 
for i in range(13):
    load_data_strings[:,0] = np.where(load_data_strings[:,0] == months[i], i, load_data_strings[:,0])    

In [30]:
np.unique(load_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [31]:
#manipulating the second column from load_data_strings - loan_status
#organize the elements of loan_status into good and bad practices 
#good practices (denotes '1') includes - Fully Paid, In Grace Period, Issued, Late (16-30 days) where 
#bad practices (denotes '0') includes - Charged Off, Current, Default, Late (31-120 days)
load_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [32]:
np.unique(load_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [33]:
np.unique(load_data_strings[:,1]).size

9

In [34]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [35]:
load_data_strings[:,1] = np.where(np.isin(load_data_strings[:,1], status_bad), 0, 1)

In [36]:
np.unique(load_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [37]:
#working on third column from load_data_strings - term 
load_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [38]:
np.unique(load_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [39]:
#split text and numeric separatly 
load_data_strings[:,2] = np.chararray.strip(load_data_strings[:,2], " months")
load_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [40]:
#replace empty data ('') with value 60
load_data_strings[:,2] = np.where(load_data_strings[:,2] == '', 60, load_data_strings[:,2])
load_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [41]:
np.unique(load_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [42]:
#now we manipulate the data from grade and subgrade columns of the dataset
np.unique(load_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [43]:
np.unique(load_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [44]:
#now replacing all missing values with the highest value in particular section like with A5 etc
for i in np.unique(load_data_strings[:,3])[1:]:
    load_data_strings[:,4] = np.where((load_data_strings[:,4] == '') & (load_data_strings[:,3] == i),
                                      i + '5',
                                      load_data_strings[:,4])

In [45]:
np.unique(load_data_strings[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [46]:
load_data_strings[:,4] = np.where(load_data_strings[:,4] == '5',
                                      'H1',
                                      load_data_strings[:,4])

In [47]:
np.unique(load_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [48]:
#removing grade column from the dataset 
load_data_strings = np.delete(load_data_strings, 3, axis = 1)

In [49]:
load_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [50]:
header_strings = np.delete(header_strings, 3)

In [51]:
header_strings

array(['issue_d', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [52]:
#now we replace the subgrade alphabetically text with integers values 
np.unique(load_data_strings[:,3])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [53]:
keys = list(np.unique(load_data_strings[:,3]))
values = list(range(1, np.unique(load_data_strings[:,3]).shape[0] + 1))
dict_grade = dict(zip(keys, values))

In [54]:
dict_grade

{'': 1,
 'A1': 2,
 'A2': 3,
 'A3': 4,
 'A4': 5,
 'A5': 6,
 'B1': 7,
 'B2': 8,
 'B3': 9,
 'B4': 10,
 'B5': 11,
 'C1': 12,
 'C2': 13,
 'C3': 14,
 'C4': 15,
 'C5': 16,
 'D1': 17,
 'D2': 18,
 'D3': 19,
 'D4': 20,
 'D5': 21,
 'E1': 22,
 'E2': 23,
 'E3': 24,
 'E4': 25,
 'E5': 26,
 'F1': 27,
 'F2': 28,
 'F3': 29,
 'F4': 30,
 'F5': 31,
 'G1': 32,
 'G2': 33,
 'G3': 34,
 'G4': 35,
 'G5': 36}

In [55]:
for i in np.unique(load_data_strings[:,3]):
    load_data_strings[:,3] = np.where(load_data_strings[:,3]==i,
                                     dict_grade[i],
                                     load_data_strings[:,3])

In [56]:
np.unique(load_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [57]:
#now forward by manipulating the verification_status column
load_data_strings[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [58]:
np.unique(load_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [59]:
#here we take '' as a Not Verified and other as same
load_data_strings[:,4] = np.where((load_data_strings[:,4] == '') | (load_data_strings[:,4] == 'Not Verified'), 0 , 1)

In [60]:
np.unique(load_data_strings[:,4])

array(['0', '1'], dtype='<U69')

In [61]:
#take a look into another column named URL and analyze it
load_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [62]:
#remove common text from the url
load_data_strings[:,5] = np.chararray.strip(load_data_strings[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")
load_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [63]:
#take a look into ID column
columns_name_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [64]:
load_data_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [65]:
load_data_strings[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [66]:
np.array_equal(load_data_numeric[:,0].astype(dtype = np.int32), load_data_strings[:,5].astype(dtype = np.int32))

True

In [67]:
#working with the state address and sor 
load_data_strings[:,6]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [68]:
np.unique(load_data_strings[:,6])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [69]:
np.sort(np.unique(load_data_strings[:,6]))

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [70]:
states_name, states_counts = np.unique(load_data_strings[:,6], return_counts = True)
states_count_sorted = np.argsort(-states_counts)
states_name[states_count_sorted], states_counts[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [71]:
load_data_strings[:,6] = np.where(load_data_strings[:,6] == '', 0, load_data_strings[:,6])
np.unique(load_data_strings[:,6])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [72]:
#refer this link for more explaination: https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf
#here we catergorize the state name according zone wise in the integer form 
#like states present in states_west zone denoted by '1' and similarly for others 
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [73]:
load_data_strings[:,6] = np.where(np.isin(load_data_strings[:,6], states_west), 1, load_data_strings[:,6])
load_data_strings[:,6] = np.where(np.isin(load_data_strings[:,6], states_south), 2, load_data_strings[:,6])
load_data_strings[:,6] = np.where(np.isin(load_data_strings[:,6], states_midwest), 3, load_data_strings[:,6])
load_data_strings[:,6] = np.where(np.isin(load_data_strings[:,6], states_east), 4, load_data_strings[:,6])

In [74]:
np.unique(load_data_strings[:,6])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [75]:
#let's check full dataset and its type now
load_data_strings

array([['5', '1', '36', ..., '1', '48010226', '1'],
       ['0', '1', '36', ..., '1', '57693261', '4'],
       ['9', '1', '36', ..., '1', '59432726', '4'],
       ...,
       ['6', '1', '36', ..., '1', '50415990', '1'],
       ['4', '1', '36', ..., '1', '46154151', '3'],
       ['12', '1', '36', ..., '0', '66055249', '3']], dtype='<U69')

In [76]:
#datatype is string 
#convert the string data type into numbers 
load_data_strings = load_data_strings.astype(dtype = np.int32)
load_data_strings

array([[       5,        1,       36, ...,        1, 48010226,        1],
       [       0,        1,       36, ...,        1, 57693261,        4],
       [       9,        1,       36, ...,        1, 59432726,        4],
       ...,
       [       6,        1,       36, ...,        1, 50415990,        1],
       [       4,        1,       36, ...,        1, 46154151,        3],
       [      12,        1,       36, ...,        0, 66055249,        3]])

In [77]:
#here we can see all data now in integer 
#and the id and url columns are same so we can delete url column as required

In [78]:
#checkpoint for strings 
checkpoint_strings = checkpoint("checkpoint-strings", header_strings, load_data_strings)

In [79]:
checkpoint_strings["header"]

array(['issue_d', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [80]:
checkpoint_strings["data"]

array([[       5,        1,       36, ...,        1, 48010226,        1],
       [       0,        1,       36, ...,        1, 57693261,        4],
       [       9,        1,       36, ...,        1, 59432726,        4],
       ...,
       [       6,        1,       36, ...,        1, 50415990,        1],
       [       4,        1,       36, ...,        1, 46154151,        3],
       [      12,        1,       36, ...,        0, 66055249,        3]])

In [81]:
np.array_equal(load_data_strings, checkpoint_strings["data"])

True

In [82]:
#Now we are manipulating numeric data 
#return numeric data
load_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [83]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [84]:
#check for missing values in numeric data
np.isnan(load_data_numeric).sum()

0

In [85]:
#check for filler values 
filler_max

68616520.0

In [86]:
np.isin(load_data_numeric[:,0], filler_max)

array([False, False, False, ..., False, False, False])

In [87]:
np.isin(load_data_numeric[:,0], filler_max).sum()

0

In [88]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [89]:
filler_stats[:, columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [90]:
#looking into funded_amount column of numeirc data
load_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [91]:
np.unique(load_data_strings[:,2])

array([36, 60])

In [92]:
#set funded_amount column equal to filler_max value and check for minimum
load_data_numeric[:,2] = np.where(load_data_numeric[:,2] == filler_max, 
                                 filler_stats[0, columns_numeric[2]],
                                 load_data_numeric[:,2])

In [93]:
load_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [94]:
filler_stats[0, columns_numeric[3]]

6.0

In [95]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [96]:
#working with loan_amnt, int_rate, installment
for i in [1,3,4,5]:
    load_data_numeric[:,i] = np.where(load_data_numeric[:,i] == filler_max, 
                                 filler_stats[2, columns_numeric[i]],
                                 load_data_numeric[:,i])
    

In [97]:
load_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [98]:
#now we are going convert currency from EUR to USD
EUR_USD = np.genfromtxt("D:\Data Analytics\Data Analyst Course\S28 - A Loan Data Example with NumPy\EUR-USD.csv",
                       delimiter = ',',
                       autostrip = True,
                       skip_header = 1,
                       usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [99]:
#return loan month 
#month reprsented by integers values from 1 to 12
#and 0 represented to mean of the data
load_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [100]:
exchange_rate = load_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)
    
    exchange_rate = np.where(exchange_rate == 0,
                            np.mean(EUR_USD),
                            exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [101]:
load_data_numeric.shape

(10000, 6)

In [102]:
exchange_rate.shape

(10000,)

In [103]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [104]:
#let add the exchange_rate data into load_data_numeric by using hstack() function
load_data_numeric = np.hstack((load_data_numeric, exchange_rate))
load_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [105]:
#add header into new column we just added
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))

In [106]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [107]:
#here in header we can see loan_amnt, funded_amnt, installment, total_pymnt are in dollars
#so we store them in a new variable 
column_dollar = np.array([1,2,4,5])

In [108]:
#return data corresponding to dollars
load_data_numeric[:,[column_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [109]:
load_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [110]:
#now we convert EURO into USD 
for i in column_dollar:
    load_data_numeric = np.hstack((load_data_numeric, np.reshape(load_data_numeric[:,i] / load_data_numeric[:,6], (10000,1))))

In [111]:
load_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [112]:
load_data_numeric.shape

(10000, 11)

In [113]:
#now we add EUR after the column having currency in EUR
#store that header in another variable
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[column_dollar]] )

In [114]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [115]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [116]:
#represent dollar currency in USD
header_numeric[column_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[column_dollar]] )

In [117]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [118]:
#we rearrange the column to EUR follows by USD 
column_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [119]:
header_numeric = header_numeric[column_index_order]

In [120]:
load_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [121]:
load_data_numeric = load_data_numeric[:,column_index_order]

In [122]:
load_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [123]:
#now we see last column of numeric dataset - interest_rate
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [124]:
load_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [125]:
#the data above is much high in numeric and not in specific form                                 #doubt
#so we change this number into percentile form 
load_data_numeric[:,5] = load_data_numeric[:,5]/100
load_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

In [126]:
#we create checkpoint for numeric data
checkpoint_numeric = checkpoint('checkpoint-numeric', header_numeric, load_data_numeric)

In [127]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

In [128]:
#upto this we organize and manipulate the numeric and strings dataset respectively

**NOW COMBINE OUR PREPROCESSED DATA OF NUMERIC AND TEXT DATA TOGETHER**

In [129]:
#complete the all dataset 
#to stack them we need to check the shape of the both dataset
load_data_strings.shape

(10000, 7)

In [130]:
load_data_numeric.shape

(10000, 11)

In [131]:
#so both dataset have same number of rows, so we can stack them horizontally 
load_data = np.hstack((load_data_strings, load_data_numeric))

In [132]:
load_data

array([[   5.  ,    1.  ,   36.  , ..., 9452.96, 8624.69,    1.1 ],
       [   0.  ,    1.  ,   36.  , ..., 4679.7 , 4232.39,    1.11],
       [   9.  ,    1.  ,   36.  , ..., 1969.83, 1750.04,    1.13],
       ...,
       [   6.  ,    1.  ,   36.  , ..., 2185.64, 1947.47,    1.12],
       [   4.  ,    1.  ,   36.  , ..., 3199.4 , 2878.63,    1.11],
       [  12.  ,    1.  ,   36.  , ...,  301.9 ,  276.11,    1.09]])

In [133]:
load_data.shape

(10000, 18)

In [134]:
#now check for missing value, if any 
np.isnan(load_data).sum()

0

In [135]:
#now combine the header of numeric and text data together 
header_full = np.concatenate((header_numeric, header_strings))

In [136]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_d', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [137]:
#now the sort the combined data for easy understand
#sort the data by url 
load_data = load_data[np.argsort(load_data[:,16])]

In [138]:
np.argsort(load_data[:,16])

array([   0,  261,  260, ..., 9971, 9973, 9999], dtype=int64)

In [140]:
#now let stack the header and data together using vstack
load_data = np.vstack((header_full, load_data))
load_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'verification_status', 'url', 'addr_state'],
       ['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'verification_status', 'url', 'addr_state'],
       ['0.0', '1.0', '60.0', ..., '0.0', '0.0', '1.1056866943836212'],
       ...,
       ['11.0', '1.0', '36.0', ..., '41913.62', '39604.60026105472', '1.0583018064498901'],
       ['11.0', '1.0', '60.0', ..., '41913.62', '39604.60026105472', '1.0583018064498901'],
       ['11.0', '1.0', '36.0', ..., '41913.62', '39604.60026105472', '1.0583018064498901']],
      dtype='<U32')

In [141]:
load_data = np.delete(load_data,0, axis = 0)
load_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'verification_status', 'url', 'addr_state'],
       ['0.0', '1.0', '60.0', ..., '0.0', '0.0', '1.1056866943836212'],
       ['12.0', '1.0', '36.0', ..., '0.0', '0.0', '1.093398094177246'],
       ...,
       ['11.0', '1.0', '36.0', ..., '41913.62', '39604.60026105472', '1.0583018064498901'],
       ['11.0', '1.0', '60.0', ..., '41913.62', '39604.60026105472', '1.0583018064498901'],
       ['11.0', '1.0', '36.0', ..., '41913.62', '39604.60026105472', '1.0583018064498901']],
      dtype='<U32')

In [142]:
#save the clean and pre-process data into system
np.savetxt("D:\Data Analytics\Data Analyst Course\S28 - A Loan Data Example with NumPy\loan-data-Preprocess.csv",
           load_data,
          fmt = "%s",
          delimiter = ',')